### PR TITLE
Filter fix

### PR DESCRIPTION
**Pull request by linkanon**
Fixed mod list ignoring filtering after performing some operations like mod synchronization and removal.

### CODE REVIEW

**Comment by patrickb8man** [comment]
Is the IntelliSense documentation enough, or would you like me to write more?

**Comment by aa2gcoder** [comment]
IntelliSense is enough, I guess. I would appreciate it if you document the parts of the code that you consider to be tricky/counter-intuitive though. Don't bother with UI docs.

Don't expect a lot of commits, honestly. I'll be mostly informing you about feature requests and bugs. Filter fix was easier to fix than to bother you with it. 

I've got lots of work snowballed so no idea when I'll touch the code though. If I do I'll try to make something like a hard linker plugin that uses json configuration.

**Comment by patrickb8man** [comment]
I'll add as much documentation as I can for big/messy parts like the main installation function, but for now my focus is on AA2Snowflake.

I was actually planning on integrating the hardlinker with this, but that never came to fruition because I was spending time on other features. You can see that in the settings where there is an unused field for the textures folder. I'll work on implementing a plugin system for the time being.

**Comment by aa2gcoder** [comment]
Yeah AA2Snowflake should be a priority imo as well. AA2Install does it's job and that bugfix was just something that bothered me. Definitely doesn't warrant an update.

I saw that field and got the idea that you had it planned. If I get to it before you I can convert the batch to json or xml (preferably json, I suppose). I used batch for transparency and that it's easy to make junctions.

**Pull request merged**
